### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by heiheshang** [emqx/emqtt#130]
`quicer/c_src/quicer_config.c:324:37: error: passing argument 3 of ‘enif_get_uint64’ from incompatible pointer type [-Werror=incompatible-pointer-types]
if (!enif_get_uint64(env, evalue, &value0))
/home/pi/erl/24.0.2/usr/include/erl_nif_api_funcs.h:135:89: note: expected ‘ErlNifUInt64 *’ {aka ‘long long unsigned int ’} but argument is of type ‘long unsigned int ’
ERL_NIF_API_FUNC_DECL(int,enif_get_uint64,(ErlNifEnv, ERL_NIF_TERM term, ErlNifUInt64 ip));
~~~~~~~~~~~~~~^~
/home/pi/erl/24.0.2/usr/include/erl_nif.h:345:76: note: in definition of macro ‘ERL_NIF_API_FUNC_DECL’

define ERL_NIF_API_FUNC_DECL(RET_TYPE, NAME, ARGS) extern RET_TYPE NAME ARGS
                                                                        ^~~~
cc1: all warnings being treated as errors
make[3]: *** [CMakeFiles/quicer_static.dir/build.make:76: CMakeFiles/quicer_static.dir/c_src/quicer_config.c.o] Error 1
`
erlang 24.0.2
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

**Comment by qzhuyan** [comment]
thanks for reporting, 
duplicated issue as in https://github.com/emqx/quic/issues/42
