### ISSUE TITLE
How to wait for receiving PUBACK message ? 

### ISSUE THREAD

**Issue by zyy17** [emqx/emqtt#14]
I write the following simple test code :

``` erlang
...
    %% connect MQTT broker
    {ok, Client} = emqttc:start_link([{host, Host}, {port, Port}, {client_id, ClientId}, {proto_ver, 3},
                       {username, UserName}, {password, Password}]),

    %% publish the message
    emqttc:publish(Client, ?TEST_TOPIC, ?TEST_PAYLOAD, qos1),
...
```

If I don't use delay, the client cannot received the PUBACK, is it correct ? 
Have you ever consider to add a new state like 'waiting_for_puback' ( looks like 'waiting_for_connack' ) ?

**Comment by erylee** [comment]
@GhostComputing, emqttc handles the PUBACK quietly and will not tell the user when PUBACK is ok.

If you want to know the PUBACK, I could add a "emqttc:sync_publish/1" API looks like:

```erlang
-spec sync_publish(Client, Topic, Payload, Qos) -> ok | {error, timeout}
```

**Comment by GhostComputing** [comment]
@erylee , thanks ! I am really looking forward to it . ^__^

**Comment by erylee** [comment]
@GhostComputing, Support synchronous subscribe/publish APIs in 0.5.0 release

Please check pull request: https://github.com/emqtt/emqttc/pull/15

**Comment by gilbertwong96** [comment]
The emqtt has released the latest version which has supported the features you desired.
