### ISSUE TITLE
Cannot connect with certificate

### ISSUE THREAD

**Issue by sangeverybusy** [emqx/emqtt#148]
2022-01-25 12:22:21.884 [error] 10.10.10.102:56122 [MQTT] 
Parse failed for function_clause
[{emqx_frame,parse_utf8_string,
             [<<1,0,225>>],
             [{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},
              {line,419}]},
 {emqx_frame,parse_packet,3,
             [{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},
              {line,165}]},
 {emqx_frame,parse_frame,4,
             [{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_frame.erl"},
              {line,142}]},
 {emqx_connection,parse_incoming,3,
                  [{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},
                   {line,503}]},
 {emqx_connection,handle_msg,2,
                  [{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},
                   {line,496}]},
 {emqx_connection,process_msg,3,
                  [{file,"/emqx-rel/_build/emqx/lib/emqx/src/emqx_connection.erl"},
                   {line,284}]},
 {proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
Frame data:<<22,3,1,0,225,1,0,0,221,3,3,21,199,146,97,105,224,11,127,38,106,76,
             205,9,193,63,199,195,242,103,13,191,17,227,214,14,254,5,188,252,
             168,196,176,32,220,19,49,190,244,216,31,223,97,172,124,232,232,
             153,23,246,205,63,72,151,23,199,165,188,106,213,227,251,153,9,10,
             166,0,36,19,1,19,2,19,3,192,47,192,43,192,48,192,44,204,169,204,
             168,192,9,192,19,192,10,192,20,0,156,0,157,0,47,0,53,0,10,1,0,0,
             112,0,23,0,0,255,1,0,1,0,0,10,0,8,0,6,0,29,0,23,0,24,0,11,0,2,1,0,
             0,35,0,0,0,13,0,20,0,18,4,3,8,4,4,1,5,3,8,5,5,1,8,6,6,1,2,1,0,51,
             0,38,0,36,0,29,0,32,152,122,105,117,220,113,210,89,212,169,203,43,
             23,66,115,27,90,242,129,123,161,108,63,178,84,141,30,44,170,174,
             218,59,0,45,0,2,1,1,0,43,0,5,4,3,4,3,3>>

**Comment by sangeverybusy** [comment]
parse_utf8_string--Changed to UTF-8. The problem remains.

**Comment by zmstone** [comment]
This looks like crash log from emqx 4.2 or earlier.
Reported to the wrong repo? Should be https://github.com/emqx/emqx.git instead.

This is a typical error message when malformed MQTT message is received by the broker.
Some random bytes were sent as the mqtt attributes which are supposed to be utf8 characters
