### ISSUE TITLE
Create new connection

### ISSUE THREAD

**Issue by maximilyin** [emqx/emqtt#152]
Why I need to execute tho functions for creating a connection? The first one you need to call emqtt:start_link(Opts) and then emqtt:connect(Pid). What's the point in that?

**Comment by zmstone** [comment]
not sure why
it could be handy to have a `emqtt:connect(Opts)` which calls `start_link` and then `connect`. 
PR is welcome

**Comment by maximilyin** [comment]
It could be handy to have one function for connecting to broker. If you need a process for saving options or have connection state you can hide it under the hood of one function. I don't see any advantages when in your solution which calls start_link and then connect
