### ISSUE TITLE
Connecting in Elixir

### ISSUE THREAD

**Issue by ovaris** [emqx/emqtt#172]
Hi, simple newbie question, I'm not able to connect, I'm simply trying this:

```
iex(4)> {:ok, pid} = :emqtt.start_link(host: '127.0.0.1', port: 1883)                          
{:ok, #PID<0.544.0>}
iex(5)> :emqtt.connect(pid) 
** (EXIT from #PID<0.538.0>) shell process exited with reason: shutdown: :econnrefused
```

```
elixir --version
Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.0 (compiled with Erlang/OTP 25)
```

`{:emqtt, github: "emqx/emqtt", tag: "1.6.1"},`

What I'm doing wrong?

**Comment by thalesmg** [comment]
Hi @ovaris !

The `:econnrefused` error hints that there may be no server listening in your local host at port 1883.

Have you confirmed that there is one?

E.g.: `nc -zv 127.0.0.1 1883`

**Comment by ovaris** [comment]
> nc -zv 127.0.0.1 1883

Indeed it's not running `nc: connectx to 127.0.0.1 port 1883 (tcp) failed: Connection refused`

But the question is why it's not up and running? Am I providing opts wrong?

**Comment by ovaris** [comment]
Okay, like I said, I'm newbie. I need to run the actual broker first i.e 
```
docker pull emqx/emqx:5.0.8
docker run -d --name emqx -p 1883:1883 -p 8083:8083 -p 8084:8084 -p 8883:8883 -p 18083:18083 emqx/emqx:5.0.8
```

Major 🤦

**Comment by thalesmg** [comment]
Glad you got it working!  :beers:
