### ISSUE TITLE
If broker is not pinged?

### ISSUE THREAD

**Issue by HtmlRanger** [emqx/emqtt#18]
I had a problem with checking of the broker. If the broker is not available, when the emqttc: start_link ([{host, "localhost"}, {client_id, << "simpleClient" >>}]), the process falls from {shutdown, econnrefused}. It is possible to check the operation of the broker?

**Comment by gilbertwong96** [comment]
This issue is for ages and we have released a new client whose implementation is totally from the old one. Please try it !
