### ISSUE TITLE
Typo `clietntid` -> `clientid`?

### ISSUE THREAD

**Issue by datafoo** [emqx/emqtt#199]
Did https://github.com/emqx/emqtt/commit/cfd3b73d5552d5ff625cfa92a4ed99569c2b558d introduce a typo `clietntid` -> `clientid`?

https://github.com/emqx/emqtt/blob/77d7de5af10f9a6331f74ebd01fec87b4617afd4/src/emqtt.erl#L338

**Comment by brianmay** [comment]
Probably this can be closed now...
