### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by heiheshang** [emqx/emqtt#204]
`[ 86%] Building C object CMakeFiles/quicer_static.dir/c_src/quicer_listener.c.o
cc1: error: too many filenames given; type ‘cc1 --help’ for usage
cc1: error: too many filenames given; type ‘cc1 --help’ for usage
cc1: error: too many filenames given; type ‘cc1 --help’ for usage
cc1: fatal error: CMakeFiles/quicer_static.dir/c_src/quicer_nif.c.d: Нет такого файла или каталога
compilation terminated.
`
trying to build v 1.2.4

**Comment by id** [comment]
@qzhuyan FYI

**Comment by qzhuyan** [comment]
which OS and which GCC version are you using?  
It should compile on major OS releases.

**Comment by heiheshang** [comment]
`NAME="openSUSE Tumbleweed"
# VERSION="20230816"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20230816"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20230816"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"`

 gcc --version
gcc (SUSE Linux) 13.2.1 20230803 [revision cc279d6c64562f05019e1d12d0d825f9391b5553]
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by qzhuyan** [comment]
close due to stale
