### ISSUE TITLE
TLS/SSL ca cert configuration for Elixir

### ISSUE THREAD

**Issue by biospank** [emqx/emqtt#208]
Hi,
I've got a subscription to Emqx Serverless and I'm trying to build my app with Elixir.
Following the tutorial https://www.emqx.com/en/blog/mqtt-for-elixir I setup the Elixir app using GenServer to connect to emqx serverless broker. 

My config.exs looks like this:

```
config :ctn, :emqtt,
  host: "xxxx.xxx.xxxxxxxx.xxxx.xxxx",
  port: 8883,
  ssl: true,
  ssl_opts: [
    cacertfile: System.get_env("CERT_HOME"),
  ],
  username: "xxxxxxxxxxx",
  password: "xxxxxxxxxxx",
  proto_ver: "v3",
  clean_start: false

```
Where my $CERT_HOME env variable point to 'priv/ssl/emqxsl-ca.crt' downloaded from my emqx serverless console

When I run my app I get this error:

```
[notice] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:2140 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
[notice] Application ctn exited: shutdown

```
Is the above Elixir configuration correct?

Any suggestion would be really appreciated.

Cheers

**Comment by biospank** [comment]
Hi @id,
here is the log:

```
[info] Starting Receiver...
[info] Initializing Receiver...
[info] ssl_opts: [verify: :verify_peer, cacertfile: "priv/ssl/emqxsl-ca.crt"]
[info] Connecting Receiver...
[notice] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:2140 generated CLIENT ALERT: Fatal - Handshake Failure
 - {:bad_cert, :hostname_check_failed}
[notice] Application ctn exited: shutdown
```

**Comment by id** [comment]
@biospank thanks, I'll try to reproduce this with serverless later today or tomorrow.

**Comment by id** [comment]
There are couple of issues:
- the `emqxsl-ca.crt` CA does not contain the intermediate one which was used to sign server certificate (I've notified the EMQ cloud team already)
- you need to enable `customize_hostname_check` in ssl_opts to enable validation of the wildcard server certificate
- you also need to enable `server_name_indication` option to enforce hostname validation, otherwise ssl library will try to validate ip address instead

Here is how to solve it step by step:

1. Download intermediate certificate. You can find the same link in the 'Authority Information Access' section of the server certificate:

> Authority Information Access:
>   OCSP - URI:http://ocsp.digicert.com
>   CA Issuers - URI:http://cacerts.digicert.com/EncryptionEverywhereDVTLSCA-G1.crt
> 

```
wget https://cacerts.digicert.com/EncryptionEverywhereDVTLSCA-G1.crt.pem
```

2. Generate CA chain with intermediate cert:
```
$ cat EncryptionEverywhereDVTLSCA-G1.crt.pem emqxsl-ca.crt > priv/ssl/ca.pem
```

3. Update `ssl_opts` in config.exs to look like this (`server_name_indication` value must be the same as `host`):
```
  ssl_opts: [
    cacertfile: 'priv/ssl/ca.pem',
    verify: :verify_peer,
    customize_hostname_check: [
      match_fun: :public_key.pkix_verify_hostname_match_fun(:https)
    ],
    server_name_indication: 'xxxx.xxx.xxxxxxxx.xxxx.xxxx'
  ],

```

Please let me know if this works.

**Comment by biospank** [comment]
Hi @id, sorry for the late reply.
I followed the instructions step by step.

1. Downloaded the intermediate certificate
2. Generated the intermediate cert
3. Updated the `ssl_opts` in the config.exe

Once the ca.pem is in place I run the app I get the following outuput:

```
[info] Starting Receiver...
[info] Initializing Receiver...
[info] ssl_opts: [verify: :verify_peer, cacertfile: "priv/ssl/ca.pem", customize_hostname_check: [match_fun: #Function<6.72213284/2 in :public_key.pkix_verify_hostname_match_fun/1>], server_name_indication: "xxxx.xxx.xxxxxxxx.xxxx.xxxx"]
[info] Connecting Receiver...
[notice] Application ctn exited: shutdown

```
This time with no feedback errors from the server. 
The above log from my GenServer runs 4 times then stop as expected.

Have you got a working sample that I can borrow to get inspiration from?

Thank you

**Comment by id** [comment]
@biospank I just tested https://github.com/emqx/MQTT-Client-Examples/blob/master/mqtt-client-Elixir/mqtt_tls.exs, and it worked even without `customize_hostname_check` option. I only replaced "broker.emqx.io" in both `host` and `server_name_indication` fields with my endpoint, and created an account with `user`/`password` credentials in the "Authentication" section of my deployment.
Note that in the examples it tries to connect to the broker 2 times, first correctly, and then incorrectly.

**Comment by id** [comment]
Please make sure you are using Erlang/OTP 25.*, and not 26. We've seen some issues with emqtt on 26 and did not have time to troubleshoot yet.

**Comment by biospank** [comment]
@id I had a look at the example and found the offending line on `server_name_indication` configuration value:

It works only if I use single quoted value like this

`server_name_indication: 'xxxx.xxx.xxxxxxxx.xxxx.xxxx'`

On double quoted value

`server_name_indication: "xxxx.xxx.xxxxxxxx.xxxx.xxxx"`

it doesn't work.

Thank you so much for your support.

Cheers
