### ISSUE TITLE
Topic Alias after reconnecting

### ISSUE THREAD

**Issue by emiltin** [emqx/emqtt#240]
My clients are connected to an emxq broker running locally in a docker container. Clients use the reconnect option.

Things work as expected, I can subscribe to a topic in a client, and publish to the topic in another. When publishing repeatedly to the same topic, the subscribing client receive messages with full topics, while Topic-Alias is not set.

When I stop and restart the emqx broker, both clients reconnect. But now when the client publish to the topic, the other client starts receiving publish messages where the topic is empty, and an Topic-Alias property is instead set.

1. Is it expected to receive publish messages where topic is empty? this would imply that my app must handle alias-to-topic mapping.

2. How can I control the use of topic alias when connecting?

**Comment by emiltin** [comment]
I never want to use topic aliases and after the initial connect they are not used. 
After a reconnect the first messages have a topic path, but the following messages have an empty topic and instead uses an alias.

**Comment by qzhuyan** [comment]
> After a reconnect the first messages have a topic path, but the following messages have an empty topic and instead uses an alias.

first message, is that from broker?

**Comment by emiltin** [comment]
Do you mean whether it's retained?

**Comment by qzhuyan** [comment]
define 'first messages', is that from client(publisher) to broker or broker to subscriber?

**Comment by emiltin** [comment]
From broker to subscriber.

**Comment by qzhuyan** [comment]
ok. then it is legit. 
I haven't got time to reproduce the error you report yet.

**Comment by emiltin** [comment]
Hi, did you get a chance to look into this?

**Comment by qzhuyan** [comment]
sorry for late rely, was working on some high priority issues.
Will take a look this week.

**Comment by qzhuyan** [comment]
I couldn't find a cheap way to fix it. May have some extra opts to declare the topic alias while start the client so that the emqtt does not need to parse and check the topics for every mqtt packet .

**Comment by emiltin** [comment]
Than you for looking into it. I think emqt needs to replace alias with the correct topic? I don't feel it makes sense to push the responsibility for handling aliases to the user of the emqt library.

**Comment by zmstone** [comment]
@qzhuyan thank you for the investigation, reading through it, it seems you have managed to reproduce it.
Could you describe what’s going on? Is it a bug in emqx or emqtt?

**Comment by qzhuyan** [comment]
I didn't reproduce it, it think it just won't work.

It is a combination of *topic alias* and *reconnect*

It is a bug in emqtt that if *topic alias* is in use that after *reconnect* it shoots inflight messages which use topic alias as the original. 
According to MQTT spec, topic alias mapping should not survives between connections thus the correct behaviour should be the emqtt sending inflight message with filling full topic instead of using topic alias.

I think the solution will be callback to the caller for filling the topics if the message use topic alias  as there is performance penalty if we track it in emqtt.

**Comment by emiltin** [comment]
Emqtt can already correctly replace topic aliases with the full topic, so the mechanism is there. It just stops working after a reconnect.
I hope this can be fixed in emqtt. I don't think it makes a lot of sense to require all users of emqtt to implement topic alias replacement.

**Comment by qzhuyan** [comment]
> mqtt can already correctly replace topic aliases with the full topic, so the mechanism is there. 

strange, I don't see emqtt has this capability, I will double check. 

Meanwhile let me clarify my understanding about your scenario,

You have following setup, pls make it clear that both publisher and subscriber are the emqtt client and broker is EMQX.

emqtt (publisher)  <----->  EMQX <-----> emqtt (subscriber)

1. At publisher side, you called emqtt publish API with both `Topic` and `Topic-alias` set
2. At publisher side, for 2nd message, you called emqtt publish API with only `Topic-alias` set
3. At subscriber side, you received both message with both "Topic" and `Topic-alias` set.
4. You called publish API more times, that may build up a queue in emqtt at publisher.
5. Both publisher and subscriber get disconnect and reconnected.
6. At publisher side, you called emqtt publish API with only `Topic-alias` set as the reconnect is automated without any callback.
7. At subscriber side  you received MQTT messages with `Topic-alias` set but `Topic` unset?

**Comment by emiltin** [comment]
Yes, I'm using emqtt for for publisher and subscriber, and EMQT as the broker.

* emqtt 1.11.0 (https://github.com/emqx/emqtt.git) (rebar3)
  locked at c815a18

> strange, I don't see emqtt has this capability, I will double check. 

You're right. I took another look at this and it seems emqtt never replaces topic aliases with the real topic.

So my original thought that this is related to reconnects seems to be wrong. Rather emqtt is simply never replacing alias with the real topic.

What is a bit confusing to me is that emqtt/EMQX will replace topics with aliases (if Topic-Alias-Maximum is set in properties), but will not convert the other way around.

I think it would be nice if emqtt would automatically convert an alias back to the full topics. Would it be anything more than a map of alias -> full topic?


> It is a bug in emqtt that if topic alias is in use that after reconnect it shoots inflight messages which use topic alias as the original.
> According to MQTT spec, topic alias mapping should not survives between connections thus the correct behaviour should be the emqtt sending inflight message with filling full topic instead of using topic alias.

I cannot confirm this to be an issue. If i restart my subscriber, it receives messages with topic alias and full topic.

**Comment by emiltin** [comment]
I can handle topic aliases with this little helper (Elixir code):

```elixir
defmodule MyApp.AliasCache do
  def handle(alies_cache, publish) do
    case publish do
      %{topic: "", properties: %{"Topic-Alias": topic_alias}} -> { alies_cache, alies_cache[topic_alias] }
      %{topic: topic, properties: %{"Topic-Alias": topic_alias}} -> { put_in(alies_cache[topic_alias],topic), topic }
      %{topic: topic} -> { alies_cache, topic }
    end
  end
end

# in an mqtt callback
def handle_info({:publish, publish}, site) do
  {alias_cache,topic} = MyApp.AliasCache.handle(site.alias_cache, publish)
  site = %{ site | alias_cache: alias_cache }
  # now use topic...
end
```

Seems to work as expected.
But I still think it would be nice if emqtt would handle this transparently.

**Comment by emiltin** [comment]
> You called publish API more times(with only Topic-alias set)

I have never publishing with only topic alias set.

**Comment by emiltin** [comment]
OK, I will do that. Perhaps I can create a reduced code example. Thank you!

**Comment by emiltin** [comment]
I asked in the emqx repo: https://github.com/emqx/emqx/discussions/12929
