### ISSUE TITLE
Fully SSL Options Support

### ISSUE THREAD

**Issue by naihs** [emqx/emqtt#27]

**Comment by akutta** [comment]
Would be nice if when ssl is specified, the port defaults to 8883.

**Comment by erylee** [comment]
@akutta, okay, I will change the SSL port.

**Comment by gilbertwong96** [comment]
The SSl Options have been fully supported in the latest emqx. And this issue is for ages. I'll close it first. If you have the other questions, welcome to open a new issue here.
