### ISSUE TITLE
Please publish to hex

### ISSUE THREAD

**Issue by mingchuno** [emqx/emqtt#30]
Can we publish to hex? Here is the details guide. 

https://hex.pm/docs/rebar3_publish

**Comment by timbuchwaldt** [comment]
I can totally second @mingchuno on this.
I just released exmqttc, my Elixir wrapper for emqttc and it would benefit greatly from the ability of installing emqttc directly via hex: https://hex.pm/packages/exmqttc

**Comment by tkeksa** [comment]
It would be nice!

**Comment by gilbertwong96** [comment]
`emqtt` has been published into rebar3 now, however, I did some trick to let users decide whether to integrate websocket dependencies into emqtt. So I still recommend you to get dependency via git protocol rather hex.
