### ISSUE TITLE
client authentication using certificates

### ISSUE THREAD

**Issue by eshubin** [emqx/emqtt#32]
Is it possible to specify CA certificate, public and private keys as ssl options?

**Comment by erylee** [comment]
Yes. The ssl:ssloption() is defined in: http://erlang.org/doc/man/ssl.html

For example:
```
SslOpts = [{certfile, "path/to/certfile"}, 
                 {keyhole, "path/to/keyfile"},
                 {password, "password"}],
emqttc:start_link([{ssl, SslOpts}]).
```

**Comment by eshubin** [comment]
@erylee could you tag master, this functionality is not included into the last release?

**Comment by erylee** [comment]
@eshubin, still not tag.
