### ISSUE TITLE
Supervisor received unexpected message: {mqttc, _Pid, connected}

### ISSUE THREAD

**Issue by eshubin** [emqx/emqtt#33]
I started emqttc:start_link under supervisor. It looks like the client always sends a message with acknowledgement to the caller process.
Is there a way to avoid this behavior?

**Comment by mingchuno** [comment]
@eshubin I suggest you use a normal `gen_server` to warp the `emqttc:start_link` so that you have a better control and you can start the wrapper in supervisor

**Comment by gilbertwong96** [comment]
This issue is for ages and we have released a new client whose implementation is totally from the old one. Please try it !
