### ISSUE TITLE
Tag 0.7.1-beta:  auto resubscribe with the unsubscribed topic already 

### ISSUE THREAD

**Issue by huetran01** [emqx/emqtt#43]
Scenario  :  
 Performed connect to broker : 
{ok, ClientA} = emqttc:start_link([{host, "localhost"}, {client_id, <<"simpleClient">>, {logger, info}, auto_resub, {reconnect, {3, 120, 10}}]),

subscribe topic <<"mongo">> with client A 
subscribe topic <<"orange">> with client A
unsubscribe topic <<"mongo">> with client A 
At  broker admin page, see that topic <<"mongo">> already unsubscribed from subscriptions list 
Stop broker emqttd, then start broker again, and emqttc reconnected to broker successfully

Observate the issue : 
Check broker admin page again, see that topic <<"orange">> and <<"mongo">> is in subscriptions list

Expection Result:
Topic <<"mongo">> should not in subscription list

**Comment by gilbertwong96** [comment]
This bug has been fixed in the latest version of emqtt. Welcome to try it!
