### ISSUE TITLE
clean_sess is not supported

### ISSUE THREAD

**Issue by 5HT** [emqx/emqtt#49]
```
received('CONNACK', State = #proto_state{clean_sess = true}) ->
    %%TODO: Send awaiting...
    {ok, State};

received('CONNACK', State = #proto_state{clean_sess = false}) ->
    %%TODO: Resume Session...
    {ok, State};
```

can you point me any guides how to implement this in client library?

**Comment by abcd-ca** [comment]
@5HT it's [documented here](https://github.com/emqtt/emqttc#clean-session), do you know that it's not implemented? setting `clean_sess = false` doesn't appear to work from the testing I've done. Messages published with qos1 (retain false) while my client is offline are not received when the client reconnects. This is not the case when I do a standalone test with the same tests using the same broker and mosquitto_sub on the command line

**Comment by gilbertwong96** [comment]
`Clean Session` mechanism is normal in the latest emqtt implementation. Please try it.

**Comment by 5HT** [comment]
We already landed a client `emqx/emtt` in N2O: 

https://github.com/synrc/n2o/blob/master/src/mqtt/n2o_mqtt.erl

Tnanks a lot!!!
