### ISSUE TITLE
auto_resub when receive msg will cause "Unexpected Info"

### ISSUE THREAD

**Issue by dcy** [emqx/emqtt#50]
Hi!
When use ```auto_resub```.
It will cause these error when receive msg:
```
[error] [Client <0.61.0>] Unexpected Info when connected: {publish,
```

**Comment by HJianBo** [comment]
Hi @dcy

**Comment by HJianBo** [comment]
Hi @dcy 
Sorry too late reply! I can not reproduce this error, could you provide more information about this? Thanks a lot!

**Comment by chintan-mishra** [comment]
`[error] [Client <0.320.0>] Unexpected Info when waiting_for_connack: {pids,
                                                                      <0.245.0>,
                                                                      <0.319.0>}`
This message is received just before the client connects.

I am using this library in an Elixir app.

**Comment by gilbertwong96** [comment]
Sadly to tell you that the `auto_resub` mechanism has been deprecated in the latest emqtt library now.
