### ISSUE TITLE
Cannot differentiate publish from different clients

### ISSUE THREAD

**Issue by gotthardp** [emqx/emqtt#61]
From one process I make two MQTT connections and subscribe to the same topic. When a published message is received I cannot see a way to determine from which connection I received it.
```erlang
{ok, C1} = emqttc:start_link([{host, "server1"}]),
emqttc:subscribe(C1, <<"OneTopic">>),
{ok, C2} = emqttc:start_link([{host, "server2"}]),
emqttc:subscribe(C2, <<"OneTopic">>),
receive
    {publish, Topic, Payload} ->
        % Is it C1 or C2????
        io:format("Message Received from ~s: ~p~n", [Topic, Payload])
end.
```
Did you thought about this problem? A standard solution would be to include the PID (C1 or C2) into the {publish} message, however that would break backwards compatibility.
Do you see a solution other than wrapping the emqttc in another process and always establish only one emqttc connection from each process?

**Comment by terry-xiaoyu** [comment]
Rewrite the emqttc as an OTP behavior would solve such problem I think. 

I'm satisfy with the current solution, as I mostly use mqttc in my test cases. Using emqttc I can subscribe a topic and store all received messages in the current process's mailbox, and check their payload later.

I prefer your first suggestion. For backward compatibility, we can add a set of new version APIs to it, and keep the old version APIs untouched. i.e. create a new startup API named 'start_link_v2'.

**Comment by gaojulong** [comment]
我认为这个问题应该尽快解决

**Comment by gilbertwong96** [comment]
This problem has been resolved. Please try the latest emqtt.
